### ISSUE TITLE
[Question]: how to exclude the vendor/test-loader.js file in my broccoli builds?

### ISSUE THREAD

**Issue by toranb** [switchfly/ember-cli-mocha#100]
I've noticed that test-support and my vendor.js file both contain the test-loader that boots when the document.ready event is fired. This could be (in my case) because we are using an older concat project ember-cli-concat (https://github.com/jschilli/ember-cli-concat/commits/1.13-active) -> I'm mostly curious how I could manually "exclude" it in my ember-cli-build (using ember-cli 1.13.13) or if this would be an option.

Also - would having this included in test support and my vendor.js file for test builds be correct?

**update**

I did a new fresh ember app w/ ember-cli-mocha and only see test-loader in 2 places (not vendor.js)

**Comment by toranb** [comment]
Looks like this is a custom issue :) sorry for the open issue guys!

**Comment by skaterdav85** [comment]
@toranb I am running into the same thing. What was your issue?

**Comment by toranb** [comment]
@skaterdav85 are you using ember-cli-concat by chance? If so ... I was able to hack around it for the moment

https://github.com/toranb/ember-cli-concat/commit/1e7bbe10e1846baaea20b0dbde70ee6d20534be9
