### ISSUE TITLE
Support for ESLint?

### ISSUE THREAD

**Issue by nybblr** [switchfly/ember-cli-mocha#105]
I'm trying to setup ESLint with Ember CLI in place of JSHint. I can't quite seem to get `ember test` running with ESLint though:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: [
        'bower_components'
      ]
    },
    babel: {
      includePolyfill: true
    },
    'ember-cli-mocha': {
      useLintTree: false
    }
  });

  return app.toTree();
};
```

My `package.json` has:

```json
    "ember-cli-mocha": "^0.10.0",
    "ember-cli-eslint": "1.2.1",
```

The `useLintTree` seems to turn off all linting, but removing that flag still runs JSHint specs in `ember test`. Anything obvious?

Related: https://github.com/jonathanKingston/ember-cli-eslint/issues/7 @jonathanKingston

**Comment by Turbo87** [comment]
@nybblr it works fine if you update `ember-cli-eslint` to the current master. `v1.2.1` of that addon is already 7 months old and is missing some changes to make it work automatically. IMHO this issue can be closed.
