### ISSUE TITLE
Increase test timeout with `pauseTest()`

### ISSUE THREAD

**Issue by alexlafroscia** [switchfly/ember-cli-mocha#114]
Is there time way to extend the test timeout when using `pauseTest()`?  It would be really handy to make it arbitrarily long... Or at least long enough to get something done.  I feel like every time I'm debugging a test and throw in a `pauseTest()` it's a race against the clock to do something before the timeout kills my test!

**Comment by Turbo87** [comment]
this is sort-of a duplicate of https://github.com/switchfly/ember-mocha/issues/75, although I'm not sure either in which repo is should actually belong.

**Comment by alexlafroscia** [comment]
Yup, seems like a duplicate to me.  I suppose the functionality should actually exist in `ember-mocha` instead.  I'll close this in favor of that issue, since we're looking for the same thing.
