### ISSUE TITLE
Clicking a test name in the browser, Generates a wrong  URL.

### ISSUE THREAD

**Issue by Mawaheb** [switchfly/ember-cli-mocha#20]
So, When running tests, Clicking a test name is generating the wrong URL, I.E :
say, a test named `MySpecialTest` generates the URL:
`http://localhost:4200/?grep=MySpecialTest` instead of 
`http://localhost:4200/tests?grep=MySpecialTest`

**Comment by esbanarango** [comment]
@rwjblue Any plans on updating to mocha 2.1.0 soon?

**Comment by dgeb** [comment]
Please upgrade to ember-cli-mocha v0.3.0 to use the latest ember-mocha, which in turn depends on mocha 2.1.0. This problem appears to be fixed in this latest version.

**Comment by cah-briangantzler** [comment]
After recently switching to mocha from Qunit, I am still seeing this problem. Have done a lot of research, am on version 0.6.2 of ember mocha, using model 2.1.0 which it appears should have fixed the issue. 

Any suggestions on things I should check to get the correct URL being generated 

I did try installing mocha 2.2.4 with no change
