### ISSUE TITLE
Inserts to .jshintrc didn't work.

### ISSUE THREAD

**Issue by gagoman** [switchfly/ember-cli-mocha#21]
Good day.

I've followed instructions at https://www.npmjs.com/package/ember-cli-mocha and my `.jshintrc` wasn't updated.

And as for jshint 2.5.1 we can use:

    "mocha": true

not https://github.com/switchfly/ember-cli-mocha/blob/master/blueprints/ember-cli-mocha/index.js#L15

Thanks for addon.

**Comment by dgeb** [comment]
Thanks for reporting this. I've removed those jshint global declarations in v0.4.0 of ember-cli-mocha.
