### ISSUE TITLE
Generating resources produces qunit blueprints

### ISSUE THREAD

**Issue by sirneb** [switchfly/ember-cli-mocha#23]
After following the instructions to remove qunit, using `ember generate resource cat`, it will still use qunit blueprints.  But using `ember generate model cat`, it will work as intended.

**Comment by dgeb** [comment]
Looks to be a bug in ember-cli's resource blueprint, which should be triggering creation of the overridden model and route test blueprints instead of the ones in ember-cli itself.

**Comment by jluckyiv** [comment]
I have created an [issue](https://github.com/ember-cli/ember-cli/issues/3095) there. I'm also working on a PR.

**Comment by jluckyiv** [comment]
@sirneb I have a [merged PR](https://github.com/ember-cli/ember-cli/pull/3096) that fixes this issue. Meanwhile, you can patch `project_dir/node_modules/ember-cli/blueprints/resource/index.js` with the change on line 29 shown in [this diff](https://github.com/ember-cli/ember-cli/pull/3096/files?diff=unified). After that, your `ember g resource foo` should generate the tests you want.

**Comment by dgeb** [comment]
@jluckyiv great job! Thanks for patching this up.

**Comment by jluckyiv** [comment]
@dgeb Thanks! It's my first. @sirneb One other suggestion: since the PR was merged, you can make use of it by following [these directions](https://github.com/ember-cli/ember-cli#working-with-master) for using the latest master branch.

**Comment by dgeb** [comment]
> Thanks! It's my first.

:+1: :tada: :balloon: :clap:

**Comment by sirneb** [comment]
@jluckyiv thanks and great job!
