### ISSUE TITLE
Add linting via postprocessTree hook.

### ISSUE THREAD

**Issue by rwjblue** [switchfly/ember-cli-mocha#25]
Need to add `postprocessTree` to handle linting app and test trees (as added in https://github.com/ember-cli/ember-cli-qunit/pull/28 and https://github.com/ember-cli/ember-cli/pull/3094).

Also, `broccoli-jshint` allows the `testGenerator` to be configurable so the JSHint tests can now be emitted as mocha style.

**Comment by ef4** [comment]
https://github.com/switchfly/ember-cli-mocha/pull/26

**Comment by dgeb** [comment]
@rwjblue can we close this now?

**Comment by rwjblue** [comment]
Yep, Ed took care of it in #26.

**Comment by dgeb** [comment]
I thought so - thanks for comfirming :+1:
