### ISSUE TITLE
strange behavior with afterEach

### ISSUE THREAD

**Issue by SirZach** [switchfly/ember-cli-mocha#32]
afterEach is triggering before the test finishes.
```
describe('Acceptance: /element/:elementId', function () {
  this.timeout(5000);
  beforeEach(function() {
    App = startApp();
    server = fakeServer();
  });

  afterEach(function() {
    debugger;
    App.reset();
    server.restore();
  });

  it('Should show a dialog for creating a new tag when clicking the plus icon', function() {
    visit("/element/005430dc-a86b-339d-aecf-6c0500b3644e");
    click('.create-tag');

    andThen(function () {
      debugger;
      expect($('.modal .modal-header h3').text().trim()).to.equal('Add Tag');
    });
  });
});
```

The debugger triggers in the afterEach before the debugger in the actual test resetting the app and not having the DOM available anymore for the test to validate against.

**Comment by rwjblue** [comment]
@SirZach - To my knowledge, Mocha is aware of two different ways to pause a test for async: 1) returning a promise, 2) adding an argument to the `it` function callback and calling it when the asycn is finished.

You can employ those techniques a couple different ways:

```javascript

// using an argument to your test
it('Should show a dialog for creating a new tag when clicking the plus icon', function(done) {
    visit("/element/005430dc-a86b-339d-aecf-6c0500b3644e");
    click('.create-tag');

    andThen(function () {
      expect($('.modal .modal-header h3').text().trim()).to.equal('Add Tag');
    });

    andthen(function() {
      done();
    })
  });

// returning a Promise
it('Should show a dialog for creating a new tag when clicking the plus icon', function() {
    visit("/element/005430dc-a86b-339d-aecf-6c0500b3644e");
    click('.create-tag');

    return andThen(function () {
      expect($('.modal .modal-header h3').text().trim()).to.equal('Add Tag');
    });
  });
```

@dgeb - Thoughts on this one?

**Comment by SirZach** [comment]
@rwjblue I must have something else set up wrong as both of your methods were a no-go but I agree that they should work.

**Comment by dgeb** [comment]
@SirZach Yes, Mocha supports async with both promises and callbacks, as @rwjblue has shown, as well as the [ember-mocha readme](https://github.com/switchfly/ember-mocha#asynchronous-testing). Note that `beforeEach` and `afterEach` can also be async.

Here are some things to consider:
* Have you recently upgraded ember-cli-mocha (and run `ember generate ember-cli-mocha`)?
* Does this happen if you run this test in isolation? (Try adding an `.only` to `describe` or `it`)
* Perhaps some of your app's initializers are interfering with startup?
* Can you try a test that visits a parent route to ensure that it's loading correctly?
* Can you step through the test to verify how far it gets before bailing out to the `afterEach`?

**Comment by dgeb** [comment]
Please re-open if you continue to have problems.
