### ISSUE TITLE
Intent to support ember-cli-test-loader

### ISSUE THREAD

**Issue by jonathanKingston** [switchfly/ember-cli-mocha#39]
ember-cli-qunit just added the support for [ember-cli-test-loader](https://github.com/ember-cli/ember-cli-test-loader) to check that modules exist as part of the testing process:
https://github.com/ember-cli/ember-cli-qunit/commit/15651d41ad24426cc3f9f2d369ac5aa0e6a1eb1e

Would there be interest in adding support to that here?

**Comment by rwjblue** [comment]
Yes, please.  Roughly the same technique should work (only with mocha formatted test instead).

**Comment by jonathanKingston** [comment]
Working on a PR.
