### ISSUE TITLE
Export vanilla describe, so that it doesn't have to be added to added to tests/.jshintrc manually

### ISSUE THREAD

**Issue by walter** [switchfly/ember-cli-mocha#45]
I want to use Mocha's plain jane "describe" to group expectations for a particular method, but when using ember-cli-mocha, I encounter a jshint failing test because "'describe' is not defined".

Even though jshint complains, describe behaves as one would expect when using it in mocha test files.

Looks to me like all that needs be done is to add it here:

https://github.com/switchfly/ember-cli-mocha/blob/master/index.js#L56

Pretty understandable that it would have gotten missed, as everything listed is specifically added or overridden by ember-mocha.

Thanks for all your excellent work.

**Comment by dgeb** [comment]
You should be able to import `describe` from the `mocha` stub module, which ember-mocha also exports. For example: https://github.com/switchfly/ember-cli-mocha/blob/master/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js#L3

**Comment by walter** [comment]
Great. Thanks for the example!
