### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by danielmavila** [switchfly/ember-cli-mocha#53]
I'm having an issue with my tests not running. 
I followed the steps of removing qunit, installing ember-cli-mocha and running ember generate ember-cli-mocha.

When I run `ember test` or `ember test --server`, they run fine but I'm getting "No tests were run :(" as a message.

Versions:
ember: 1.11.3
ember-cli: 0.2.3
ember-cli-mocha: 0.6.0
ember-mocha: 0.6.2

**Comment by NullVoxPopuli** [comment]
why was this closed? I have an issue. 0 tests run. and my console shows:

```
Global error: Uncaught TypeError: app.testHelpers.wait is not a function at http://localhost:7357/assets/test-support.js, line 19753
```
no idea what that's about
