### ISSUE TITLE
Bring component integration test in line with ember-cli

### ISSUE THREAD

**Issue by blimmer** [switchfly/ember-cli-mocha#58]
[This PR](https://github.com/ember-cli/ember-cli/pull/4272) to ember-cli will likely be done soon and has a few differences from our implementation:

* It generates a component integration test by default when generating a new component (and allows generating a unit test by specifying `--unit`)
* It has a different argument (they use `--test-type`)
```js
  availableOptions: [
    {
      name: 'test-type',
      type: ['integration', 'unit'],
      default: 'integration',
      aliases:[
        { 'i': 'integration'},
        { 'u': 'unit'},
        { 'integration': 'integration' },
        { 'unit': 'unit' }
      ]
    }
  ]
```

Once the ember-cli PR is merged I propose we bring this project back in sync. I will gladly submit a PR for this change.

**Comment by rwjblue** [comment]
Thanks for keeping track and working on this @blimmer!

**Comment by trabus** [comment]
:+1: 
@blimmer Thanks, and sorry for any crossed wires!

**Comment by blimmer** [comment]
No problem. Happy to see this taking priority!

**Comment by blimmer** [comment]
The dependency branch was merged this morning. This can be worked whenever - I might be able to get to it this week(end)

**Comment by rwjblue** [comment]
@blimmer - Thank you!
