### ISSUE TITLE
unable to find suitable version for ember-mocha?

### ISSUE THREAD

**Issue by rvan1** [switchfly/ember-cli-mocha#59]
With my Ember CLI (0.2.3) project, I get 'not installed ember-cli-qunit', I think because CLI uses 'test em', not qunit.
I also get a few 'unmet dependency' warnings where rimraf, testem and tap require a lower version of glob, a type of problem I've seen before when installing other node modules.
When I generate 'cli-mocha', I get 'unable to find suitable version for ember-mocha'. My node modules DOES have 'mocha', but am not sure which version.
My project package json has:

    "ember-cli-mocha": "^0.8.0",
    "glob": "^4.0.5",
    "mocha": "*",
    "sinon": "*"

**Comment by rvan1** [comment]
After upgrading to ember-cli 0.2.7 & glob 5.0.10, I'm able to reinstall/update mocha and cli-mocha. I'm using an 'Ember-Mocha Tests' index.html in my 'tests' directory. When I run 'ember test --server', it still seems to want to run 'test em' and I get a script error 'could not find module ember-cli/test-loader', which also is a 'test em' dependency, not a 'mocha' dependency'. My 'index.html' expects several 'assets' js files which are 404; mocha, chai, adapter & loader.

**Comment by rvan1** [comment]
I also reinstalled 'ember-mocha' (as opposed to just 'mocha'). I also ran 'npm start', and found the test index at ...:4200/tests, which is new to me. With the other test command syntax, I would get a new window and port. Now it's not running any 'test em' or looking for 'test-loader', but the 'assets' js files are still 404. I think the command or generator should copy the needed files into 'assets'.

**Comment by blimmer** [comment]
I just ran `ember install ember-cli-mocha` on a new ember cli app and don't have this issue. Are you still having problems getting this working?

**Comment by dgeb** [comment]
Closing. @rvan1 please let us know if you have further problems.
