### ISSUE TITLE
Use `describe` to group tests

### ISSUE THREAD

**Issue by shaunc** [switchfly/ember-cli-mocha#76]
I would like to be able to group my tests together using `describe`:

    describeComponent('complex-component','lots of tests', {integration: true}, function() {
      describe('should foo', function() {
        ..
      });
      describe('should bar', function() {
        ..
      });
      ...
   });

Unfortunately I don't seem to be able to do this. I tried loading `describe` directly from `ember-mocha-adapter`, but then the suite complains about the resolver.

Is this possible? I would think this shouldn't be too hard to add.

**Comment by shaunc** [comment]
No hints on how to get "describe" to work? Short of official support, instructions for a work-around would be most welcome.

**Comment by blimmer** [comment]
You can import `describe` from mocha and use it.

```
import { describe } from 'mocha';
```

**Comment by dgeb** [comment]
Importing `describe` as @blimmer suggests is recommended. Let us know if you have any problems @shaunc.
