### ISSUE TITLE
application start and destroy hooks stop working

### ISSUE THREAD

**Issue by ballPointPenguin** [switchfly/ember-cli-mocha#77]
I'm not sure if this is the right place for this issue.
I'm just starting to build an acceptance test suite for this application. I have only 2 acceptance tests. Usually when I run them, either via ember test --server or in the browser at /tests, with either Firefox or Chrome (or even just Phantom alone), everything runs at least the first time, maybe a few times. But after a couple refreshes, things get stuck. I'm seeing

```
x "before each" hook
TypeError: Cannot read property 'default' of undefined
    at Context.<anonymous> (assets/my-app.js:29712:29)
    at invoke (assets/test-support.js:14682:21)
    at Context.asyncFn (assets/test-support.js:14667:11)
    at Hook.require.register.Runnable.run (assets/test-support.js:7144:15)
    at next (assets/test-support.js:7470:10)
    at assets/test-support.js:7491:5
    at timeslice (assets/test-support.js:9098:27)
```

```
x "after each" hook
TypeError: Cannot read property 'destroy' of undefined
    at Object.Backburner.run (assets/vendor.js:9597:26)
    at Object.run (assets/vendor.js:26104:29)
    at Context.<anonymous> (assets/my-app.js:29720:24)
    at invoke (assets/test-support.js:14682:21)
    at Context.asyncFn (assets/test-support.js:14667:11)
    at Hook.require.register.Runnable.run (assets/test-support.js:7144:15)
    at next (assets/test-support.js:7470:10)
    at assets/test-support.js:7491:5
    at timeslice (assets/test-support.js:9098:27)
```

The relevant lines in the built asset for my-app.js are:

```
    mocha.beforeEach(function () {
      application = startApp['default']();
      Ember['default'].$(document).off('click');
      Ember['default'].$(document).off('keyup');
      Ember['default'].$.removeCookie('access_token', { path: '/' });
      Ember['default'].$.removeCookie('user_id', { path: '/' });
    });

    mocha.afterEach(function () {
      Ember['default'].run(application, 'destroy');
    });
```

**Comment by ballPointPenguin** [comment]
Possibly related to https://github.com/ember-cli/ember-cli-test-loader/commit/2fca180d7f585a6863fb03e2b13db5adc8af55c5

**Comment by ballPointPenguin** [comment]
I reverted to
ember-cli-test-loader v0.1.3
and
loader.js v3.2.1
(as prescribed in the current ember-cli blueprints)
and the problem still occurs, so it is unrelated to 'unsee' and the above commit.

**Comment by rwjblue** [comment]
Seems to indicate that `startApp` isn't present.

**Comment by ballPointPenguin** [comment]
it's strange that it always works the first time. If I run ember test, it runs the whole suite. It's just when I'm reloading the suite that it gets stuck.

**Comment by aldhsu** [comment]
I am migrating an app from Ember 1.12 to 1.13.8 and seeing the same behaviour.
Tests will run initially and after a file change and tests rerunning, as @rwjblue said, startApp is no longer imported correctly and is undefined.

**Comment by ballPointPenguin** [comment]
For reference, I'm using
ember-cli 1.13.8
ember 1.10.1
io.js 2.5.0
npm 2.13.4
ember-cli-mocha 0.9.2
ember-mocha 0.8.1
ember-mocha-adapter 0.3.1
mocha 2.2.5
linux x64

**Comment by stefanpenner** [comment]
should be fixed by https://github.com/broccolijs/broccoli-filter/pull/35

**Comment by ballPointPenguin** [comment]
I can confirm that @stefanpenner's fix has solved the issue for me.
