### ISSUE TITLE
If using ES6 backtick strings for `modulePrefix`, the install fails

### ISSUE THREAD

**Issue by jfelchner** [switchfly/ember-cli-mocha#83]
```
modulePrefix : `my-module-prefix`,
```

in `environment.js` fails.

**Comment by rwjblue** [comment]
config/environment.js is evaluated in node (and is not preprocessed with Babel). Does your node version support template strings? How is this scenario tied to ember-cli-mocha?

**Comment by jfelchner** [comment]
@rwjblue my bad. This was the first time I'd ever seen it so I assumed it was.  I'll just switch to single quotes for `environment.js`. No big deal. :) Thanks!

**Comment by rwjblue** [comment]
Awesome, glad you got it sorted out!
